### ISSUE TITLE
The `aliases` configuration does not seem to work

### ISSUE THREAD

**Issue by Bastes** [mhanberg/temple#92]
**Describe the bug**
Attempting to alias functions from this awesome library to avoid name collisions (as per documentation) did not yield the expected result.

**To Reproduce**
```
# in config/config.exs
config :temple, :aliases, link: :_link
# or
config :temple, :aliases, link: :_link
# or
config :temple, aliases: %{link: :_link}
# or
config :temple, aliases: [link: :_link]
```

```
# in lib/app_web/templates/layout/app.html.exs
_link(rel: "stylesheet", href: Routes.static_path, @conn, "/css/app.css"))
```

All those configs results in warnings during compilation and an error when the server attempts to start:
```
undefined function _link/1
```

**Expected behavior**
I would expect the `<link>` tag to be generated.

**Desktop (please complete the following information):**
 - OS: [Docker's official Elixir image](https://hub.docker.com/_/elixir)
 - Temple Version: `0.6.0-alpha.4`
 - Elixir Version: `1.10.4 (compiled with Erlang/OTP 22)`
 - Erlang Version: `Erlang/OTP 22 [erts-10.7.2.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]`

**Comment by mhanberg** [comment]
Thanks for the great bug report 👍

Do you mind testing this with the master branch and seeing if it is still broken? My current project uses master as well as the integration tests, and there doesn't seem to be any broken behavior.

Thanks!

**Comment by mhanberg** [comment]
If it's fixed on master, I can push another release. I have fallen behind on releases because it was easier to just work on master for my current project.

**Comment by Bastes** [comment]
Thanks for your quick response :smiley: I'll be sure to let you know once I've tried.

**Comment by Bastes** [comment]
I just tried adding the `master` branch from this very repo:
```elixir
# src/mix.exs
defp deps do
  [
    ...
    {:temple, git: "https://github.com/mhanberg/temple.git", branch: "master"}
  ]
```
Alas it fails to compile:
```
== Compilation error in file lib/temple/parsers/components.ex ==
** (ArgumentError) could not fetch application environment :component_prefix for application :temple because the application was not loaded/started. If your application depends on :temple at runtime, make sure to load/start it or list it under :extra_applications in your mix.exs file
```
I'm not sure what I did wrong there :sweat_smile: if you see what's wrong with it don't hesitate to tell me.

**Comment by Bastes** [comment]
Good news though: it's working fine with `0.6.0-alpha.4` now. But since that's the one I had when I reached out, I can't for the love of me figure out why it wasn't before. Weird.

**Comment by Bastes** [comment]
So, I guess we can close that one?

**Comment by mhanberg** [comment]
I think there is some weirdness about recompilation that I have yet to fix yet. If something sort of configuration isn't working, I would run `mix compile --force`, (I think it also works with `mix phx.server --force`)

**Comment by Bastes** [comment]
Hi,

I'm re-opening this issue, having found an element for which `alias` does not seem to work.

To reproduce:
```elixir
# in config/config.exs
config :temple, :aliases, link: :_link, label: :_label, select: :_select

# in our view:
select(:form_name, :field_name, @options, prompt: "Choose an Option")
```
The temple version is used instead of the `Phoenix.HTML.Form` one, and of course the parameters don't work.

We don't know why but `link` and `label` are correctly aliased.

Hope it helps :)

**Comment by mhanberg** [comment]
Can you try and run `mix deps.clean temple` and try again? 

They way it's written now it's all done at compile time. So if you change you're configure, you need to make sure you recompile the Temple dep.

**Comment by Bastes** [comment]
I'll try this first chance I get :) thanks.

**Comment by Bastes** [comment]
It works :) thanks again, closing now.
